os: linux

dist: bionic

env:
    secure: "MTqhVp86DqGNiFcaLlXdvxN19bMSZYSP4t1FXZi0dZPXRw3Gpv2Bh16pCCXTK3v0512wvCX1DhRbyrpEFDzF8BhBlX0JKb/jE1d3fu7V1oS+++0XPMf5L8eZ+t4Sez4tPG3BXvCsgjJ0hlMZbcvMJuQIyQwI2/yGzKOeQ/5TDTp3n3+dgC7cEONFduYO+bEIE+q3UvbxOqYpqLUypCJgF2BcTEOTKo4KCQYVuOKvMvjkS2tXlnZylHbAL/dBlu+7Pp1v3EPex/B8hkTjea3cY9fNiV9N9rVDo49JaQxwP86fsDqy7LAh36Lea/1A/t9uXggSo/cmKb2ISN8k42cUlNFqa3oF/kX+rMGVWOfxZTxLVQfTxHjXvRUH1N6Zm9AcxTDn+QxImkiFbU1RmcXENFpmWcAfdfrqH5gnVsWj8nokby1B+Sc93heIM5ekJiJYcS9BASw20iXieUPsT79pS7hGzP7eiuu5CNibzhoLcSUwKNuM02iuVi7EKyUITkfU91/pn/3kV1a1V+KnO7qih4LJp7Ndc3CXbW6AtiP4JIKdpUf/NMr3aPUeml+OlKZsAOBm7YsUo8PHVar/sAJixQ1mcpKqnfx6MEuy9GBNPFCqUHd5qPn1Yk7OA2USxM80ZTLhpNpx4V/n6kxfCMoVvln/AO3lIrK9ZdkEDiI8q6A="

language: python

python: "3.7"

branches: master

install:
    - pip install mkdocs mdx_include mkdocs-material pymdown-extensions yafg mkdocs-macros-plugin mkdocs-htmlproofer-plugin uuid requests bs4 urllib3

script: mkdocs build --verbose --clean --strict

before_deploy:
    - mkdocs build --verbose --clean --strict

deploy:
    provider: pages
    cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: site
    on:
        branch: master