os: linux

dist: bionic

language: python

python: "3.7"

branches: master

install:
    - pip install mkdocs mdx_include mkdocs-material pymdown-extensions yafg mkdocs-macros-plugin mkdocs-htmlproofer-plugin uuid requests bs4 urllib3

script: mkdocs gh-deploy

before_deploy:
    - mkdocs build --verbose --clean --strict

deploy:
    provider: pages
    cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: site
    on:
        branch: master