site_name: DTC MkDocs POC
nav:
  - "The POC welcomes you!": index.md
  - Alma Section:
    - 'Foo': alma/foo.md
    - 'Bar': alma/bar.md
  - Barack Section:
    - 'Baz': barack/baz.md
    - 'Foobar': barack/foobar.md
docs_dir: 'docs'
theme:
  name: 'material'
  favicon: 'images/favicon.ico'
  logo: 'images/favicon.ico'
markdown_extensions:
  - yafg
  - footnotes
  - admonition
  - markdown_include.include:
      base_path: docs
  - attr_list
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences: 
        - name: flow
          class: uml-flowchart
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: sequence
          class: uml-sequence-diagram
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
extra_css:
  - css/tabbed-superfence.css