site_name: Docs-As-Code Pipeline POC
nav:
  - The POC welcomes you!: index.md
  - Alma Section:
    - 'Foo': alma/foo.md
    - 'Bar': alma/bar.md
  - Barack Section:
    - 'Baz': barack/baz.md
    - 'Foobar': barack/foobar.md
    - Sub-Nest:
        - 'Deeper Still': barack/cekla/foobaz.md
        - Sub-sub Nest:
          - "This is Foo-foo!": barack/cekla/dio/foofoo.md
          - "Also ran": barack/cekla/dio/barbar.md
  - From the Dependent Repo:
    - Can You See This?: dependency1/alma/foo.md
    - This Is a Sub-Dependency!:
      - A: dependency1/barack/wordlists/a.md
      - B: dependency1/barack/wordlists/b.md
      - C: dependency1/barack/wordlists/c.md
docs_dir: 'docs'
site_dir: 'site'
plugins:
  - search
  - htmlproofer
  - macros
theme:
  name: 'material'
  favicon: 'images/kitten.ico'
#  logo: 'images/hpe_pri_wht_rev_rgb.svg'
  logo: 'images/green-cat.png'
  custom_dir: 'theme'
  font: false
markdown_extensions:
  - tables
#  - cell_row_span
  - mdx_include
  - yafg
  - footnotes
  - admonition
#  - markdown_include.include:
#      base_path: docs
  - attr_list
#  - toc:
#      title: "How do you like my fancy TOC?"
  - sane_lists
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences: 
        - name: flow
          class: uml-flowchart
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: sequence
          class: uml-sequence-diagram
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
extra_css:
  - css/tabbed-superfence.css
extra:
  price: 12.50
  company:
    name: Acme
    address: 123 Sample Drive Yoknapatawpha